import Path

# training
TRAINING_LOOKBACK_DAYS = 365
MAX_ENCODER_LENGTH = 168
MAX_PREDICTION_LENGTH = 24

# prediction
DEFAULT_HISTORY_DAYS = 7
DEFAULT_FORECAST_HOURS = 24

# paths
AUTOMATIC_DIR = Path("automatic")
FIG_DIR = Path("figures")
